#!/bin/bash

if [ ! -f sbin/diskimg.img ]
then
  mkdir -p sbin/
  qemu-img create sbin/diskimg.img 10M
  mkfs.ext2 sbin/diskimg.img
fi

QEMU_ARGS="--enable-kvm -serial stdio -cpu qemu64 -M q35 -m 256M -boot d -smp 2 \
	-rtc base=localtime -audiodev pa,id=audio0 -machine pcspk-audiodev=audio0  -drive id=disk,file=sbin/diskimg.img,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0,serial=111111111111111111111 -netdev tap,id=br0,ifname=tap0,script=no,downscript=no -device rtl8139,netdev=br0,mac=52:55:00:d1:55:01"

echo "Creating tap interface.."
sudo ip tuntap add dev tap0 mode tap user $(id -u)
sudo ip address add $(ip route get 1.2.3.4 | awk '{print $7}') dev tap0
sudo ip link set dev tap0 up
qemu-system-x86_64 $QEMU_ARGS -cdrom MKSD.iso
echo "Removing tap interface.."
sudo ip tuntap del dev tap0 mode tap
