#!/bin/bash

if [ ! -f sbin/diskimg.img ]
then
  mkdir -p sbin/
  qemu-img create sbin/diskimg.img 10M
  # mkfs.ext2 sbin/diskimg.img
fi

QEMU_ARGS="--enable-kvm -serial stdio -cpu qemu64 -M q35 -m 256M -boot d -smp 2 \
	-rtc base=localtime -audiodev pa,id=audio0 -machine pcspk-audiodev=audio0  -drive id=disk,file=sbin/diskimg.img,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0,serial=111111111111111111111"

qemu-system-x86_64 $QEMU_ARGS -cdrom MKSD.iso
